### ISSUE TITLE
Improve Duo Validation

### ISSUE THREAD

**Issue by adamfitzgibbon** [unlhcc/HCCGo#26] opened 2016-02-15 22:25 UTC
Every time I log in, I think there has to be a better way of choosing how to login with Duo. I was thinking perhaps just radio buttons. Anything other than a text input that only accepts 3 different characters. Also I still can't assign myself issues so this should be assigned to me by anyone who can.

**Comment by djw8605** [comment] 2016-02-15 22:28
The problem is that the duo prompt, or whatever prompt we may encounter in the future, may have look different.  SSH protocol only allows for a prompt, and a text response to that prompt.  

Further, if people are using yubikeys, even in the current prompt, then they have to input the yubikey value in the text area.

**Comment by adamfitzgibbon** [comment] 2016-02-15 22:30
Oh, so it would not be possible to have radio buttons that correspond to each choice and have them return back a '1', '2', or '3'?

**Comment by djw8605** [comment] 2016-02-15 22:31
It would.  But what about people that do not duo push, and only use yubikeys.  The prompt looks different for them.  There are only 2 options, 1 is to get a text, and 2 is to receive a call.

The problem is that you probably couldn't parse every single possibility for the duo prompt.

**Comment by adamfitzgibbon** [comment] 2016-02-15 22:36
Ah I see. Probably an unnecessary thing to worry about for the time being then? Perhaps in the future when most of the major functionality is already implemented, we can take a look at polishing this kind of thing out? If at all if it actually can't be helped.

**Comment by djw8605** [comment] 2016-02-18 21:02
I'm going to close this for now.

**Closed by djw8605** 2016-02-18 21:02 UTC
Labels: enhancement
